services:
  - type: web
    name: supermemorynn
    runtime: docker
    dockerfilePath: ./Dockerfile
    plan: free
    region: oregon
    autoDeploy: true
    healthCheckPath: /healthz

    envVars:
      - key: TG_BOT_TOKEN
        sync: false
      - key: TG_CHAT_ID
        sync: false
      - key: TG_ADMIN_ID
        sync: false
      - key: MONITOR_INTERVAL
        value: "300"
      - key: MIN_BACKUP_INTERVAL_SEC
        value: "600"
      - key: FORCE_BACKUP_EVERY_SEC
        value: "21600"
      - key: CHUNK_SIZE
        value: "18M"
      - key: PORT
        value: "5678"
      - key: N8N_PORT
        value: "5678"
      - key: N8N_HOST
        value: "0.0.0.0"
      - key: N8N_PROTOCOL
        value: "https"
      - key: N8N_SECURE_COOKIE
        value: "false"
      - key: WEBHOOK_URL
        sync: false
      - key: N8N_EDITOR_BASE_URL
        sync: false
      - key: N8N_BASIC_AUTH_ACTIVE
        value: "true"
      - key: N8N_BASIC_AUTH_USER
        sync: false
      - key: N8N_BASIC_AUTH_PASSWORD
        sync: false
      - key: N8N_ENCRYPTION_KEY
        sync: false
      - key: GENERIC_TIMEZONE
        value: "Asia/Baghdad"
      - key: TZ
        value: "Asia/Baghdad"
      - key: N8N_DIAGNOSTICS_ENABLED
        value: "false"
      - key: N8N_VERSION_NOTIFICATIONS_ENABLED
        value: "false"
      - key: N8N_TEMPLATES_ENABLED
        value: "true"
      - key: N8N_SKIP_WEBHOOK_DEREGISTRATION_SHUTDOWN
        value: "true"
      - key: N8N_GRACEFUL_SHUTDOWN_TIMEOUT
        value: "30"
      - key: N8N_REINSTALL_MISSING_PACKAGES
        value: "true"
      - key: N8N_COMMUNITY_PACKAGES_ENABLED
        value: "true"
      - key: NODE_FUNCTION_ALLOW_EXTERNAL
        value: "*"
      - key: N8N_CUSTOM_EXTENSIONS
        value: "/home/node/.n8n/nodes"
      - key: N8N_DEFAULT_BINARY_DATA_MODE
        value: "filesystem"
      - key: N8N_BINARY_DATA_TTL
        value: "1"
      - key: EXECUTIONS_DATA_PRUNE
        value: "true"
      - key: EXECUTIONS_DATA_MAX_AGE
        value: "10"
      - key: EXECUTIONS_DATA_SAVE_ON_SUCCESS
        value: "none"
      - key: EXECUTIONS_DATA_SAVE_ON_ERROR
        value: "none"
      - key: EXECUTIONS_DATA_SAVE_MANUAL_EXECUTIONS
        value: "false"
      - key: EXECUTIONS_PROCESS
        value: "main"
      - key: EXECUTIONS_TIMEOUT
        value: "3600"
      - key: EXECUTIONS_TIMEOUT_MAX
        value: "7200"
      - key: NODE_OPTIONS
        value: "--max-old-space-size=512"
